version: "3"

services:
  server:
    image: ical-transformer:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "C:/Users/grego/Development/Private/ical-transformer/transformer.toml:/transformer.toml"